service: lms-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  user:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
